spring:
  redis:
    database: 0
    host: clustercfg.twn-dev-redis.7a84ec.ape1.cache.amazonaws.com
    password: 63115712A666479602726160T476894FWBFYBYTO0YEIHMXGWMDDVSVE1v6awKa1pu6MKDALN4zTO3chfK1MHCkVfJqmw48MJ1OBIDEFFKZ320665554FYJ0If5bH22F
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000
  datasource:
    url: jdbc:mysql://wp-rds-single.wealth-platform-twn.dev.aws.cloud.hsbc:3306/iseetest?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: admin
    password: admin.123

# 日志路径
logging:
  path: /appvol/app/isee/za-isee-console/logs/

isee:
  # 回调接口的加密配置 账号：密码
  callback:
    companys: {zhongan: isee123456,zhonganbaxian_zhiying: isee123456}
  # 内部服务域名
  domain:
    machine: http://10.89.18.56:8003
    convert: http://10.89.18.56:8083
    console: http://10.89.18.56:8082
    player: http://10.89.18.56:9090
  # oss地址
  oss:
    enabled: true
    ENDPOINT: http://10.89.18.56:8084/s3proxy
    ACCESSID: id
    ACCESSKEY: key
    BUCKET: data
    VIRTUAL: false
    REGION:

