spring:
  redis:
    database: 0
    host: clustercfg.twn-dev-redis.7a84ec.ape1.cache.amazonaws.com
    password: 63115712A666479602726160T476894FWBFYBYTO0YEIHMXGWMDDVSVE1v6awKa1pu6MKDALN4zTO3chfK1MHCkVfJqmw48MJ1OBIDEFFKZ320665554FYJ0If5bH22F
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000

# 日志路径
logging:
  path: /appvol/app/isee/collector/logs/

isee:
  nasStore: true
  #nas存储数据路径
  #确认该路径有可读可写权限，权限属于应用启动用户
  logdir: /appvol/logs
  # 对外sdk使用的加密信息
  sdk:
    #加密算法偏移量16位长度
    aesIv: f3k9f5z7f8u1nb20
    #加密key和secret
    accessMap:
      #key 自定义 # 密码 长度 16位
      LJo74OzuqCfxHQ7Z4Ijm: eadaf9b9b77b2920
